apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node
  namespace: simple-node
spec:
  selector:
    matchLabels:
      app: simple-node
  template:
    metadata:
      labels:
        app: simple-node
        deployment: simple-node
    spec:
      containers:
      - name: simple-node
        image: image-registry.openshift-image-registry.svc.cluster.local:5000/cicd-pipelines/simple-node:latest@sha256:57c6c733c138d0c30be3336c356f500614910fe12ba145ad70f891b288a9afb2