apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node
  namespace: simple-node
spec:
  selector:
    matchLabels:
      app: simple-node
  template:
    metadata:
      labels:
        app: simple-node
        deployment: simple-node
    spec:
      containers:
      - name: simple-node
        image: image-registry.openshift-image-registry.svc.cluster.local:5000/cicd-pipelines/simple-node:latest@sha256:fe5fbda4e797050e6c51ec31bdf9302f5e5db3fee8d3bcd33e9552eaca2f40f0