apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/

replicas:
  - name: simple-node
    count: 1

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: simple-node