apiVersion: v1
kind: Service
metadata:
  name: simple-node
  namespace: simple-node
  labels:
    app: simple-node
    app.kubernetes.io/component: simple-node
    app.kubernetes.io/instance: simple-node
    app.kubernetes.io/name: simple-node
    app.kubernetes.io/part-of: quarkus-app-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/TiagoAvelino/Simple-node-application'
    openshift.io/generated-by: OpenShiftWebConsole
    argocd.argoproj.io/sync-wave: "30"

spec:
  type: ClusterIP
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: simple-node
    deployment: simple-node