kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: simple-node
  namespace: simple-node
  uid: 4412c90d-2ae0-4cd5-991e-363c165df6f9
  resourceVersion: '304407'
  creationTimestamp: '2025-07-26T20:46:37Z'
  labels:
    app: simple-node
    app.kubernetes.io/component: simple-node
    app.kubernetes.io/instance: simple-node
    app.kubernetes.io/name: simple-node
    app.kubernetes.io/part-of: quarkus-app-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: simple-node-simple-node.apps.tiago-cluster.sandbox2099.opentlc.com
  to:
    kind: Service
    name: simple-node
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
status:
  ingress:
    - host: simple-node-simple-node.apps.tiago-cluster.sandbox2099.opentlc.com
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2025-07-26T20:46:37Z'
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps.tiago-cluster.sandbox2099.opentlc.com
